# Generated by Django 5.0.4 on 2024-05-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_registrationdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdb',
            name='Profile_Image',
        ),
    ]
