# Generated by Django 5.0.4 on 2024-05-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_remove_registrationdb_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='Confirm_Password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
