# Generated by Django 5.0.4 on 2024-06-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email_Id', models.EmailField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone_Number', models.IntegerField(blank=True, null=True)),
                ('SaySomething', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
